# Exploring MLB Offensive Performance Using SQL

This project explores offensive performance trends across MLB players and teams using SQL queries applied to 2023 batting statistics. The analysis focuses on team offensive production, plate discipline, and player performance beyond traditional home run metrics.

In [9]:
import pandas as pd
import sqlite3

df = pd.read_csv("Batting.csv", sep=";", encoding="latin1")

conn = sqlite3.connect(':memory:')
df.to_sql('batting', conn, if_exists='replace', index=False)

695

## Exploratory Analysis

Which players ranked among the league leaders in home runs?

In [10]:
query = """
SELECT Name,
       Tm,
       HR
FROM batting
ORDER BY HR DESC
LIMIT 10
"""

pd.read_sql_query(query, conn)

               Name   Tm  HR
0    Shohei Ohtani*  LAA  35
1       Matt Olson*  ATL  32
2   Luis Robert Jr.  CHW  28
3      Mookie Betts  LAD  27
4       Pete Alonso  NYM  26
5   Kyle Schwarber*  PHI  26
6     Adolis García  TEX  24
7     J.D. Martinez  LAD  24
8       Jorge Soler  MIA  24
9  Ronald Acuna Jr.  ATL  23

### Findings

Shohei Ohtani, Matt Olson, and Luis Robert Jr. ranked among the league leaders in home runs within this dataset. The results provide an initial overview of the league's top power hitters and establish context for the team-level analyses that follow.

## Research Question 1

Which teams demonstrated the strongest offensive production based on average OPS?

In [23]:
query = """
SELECT Tm,
       ROUND(AVG(OPS),3) AS Avg_OPS
FROM batting
WHERE Tm != 'TOT'
GROUP BY Tm
ORDER BY Avg_OPS DESC;
"""

pd.read_sql_query(query, conn)

     Tm  Avg_OPS
0   MIL    0.727
1   PHI    0.696
2   MIA    0.689
3   TBR    0.685
4   WSN    0.678
5   LAA    0.673
6   NYY    0.668
7   OAK    0.659
8   MIN    0.652
9   ATL    0.627
10  CLE    0.623
11  TOR    0.618
12  SDP    0.616
13  NYM    0.610
14  PIT    0.609
15  DET    0.589
16  KCR    0.584
17  COL    0.578
18  CHC    0.562
19  STL    0.557
20  TEX    0.554
21  CIN    0.534
22  BOS    0.533
23  LAD    0.528
24  CHW    0.521
25  ARI    0.521
26  SFG    0.492
27  HOU    0.475
28  BAL    0.463
29  SEA    0.433

### Findings

MIL, PHI, and MIA recorded the highest average OPS values in the dataset, indicating stronger offensive production relative to other teams in the league.

## Research Question 2

How do team home run totals compare with average offensive production?

In [18]:
query = """
SELECT Tm,
       SUM(HR) AS Total_HR,
       ROUND(AVG(OPS),3) AS Avg_OPS
FROM batting
WHERE Tm != 'TOT'
GROUP BY Tm
ORDER BY Total_HR DESC;
"""

pd.read_sql_query(query, conn)

     Tm  Total_HR  Avg_OPS
0   ATL       185    0.627
1   LAD       161    0.528
2   LAA       151    0.673
3   TBR       148    0.685
4   NYY       139    0.668
5   TEX       137    0.554
6   STL       135    0.557
7   MIN       133    0.652
8   SDP       126    0.616
9   NYM       123    0.610
10  HOU       122    0.475
11  ARI       116    0.521
12  SFG       115    0.492
13  SEA       114    0.433
14  BAL       114    0.463
15  TOR       111    0.618
16  CIN       111    0.534
17  CHW       110    0.521
18  BOS       110    0.533
19  PHI       109    0.696
20  CHC       108    0.562
21  MIL       103    0.727
22  COL        96    0.578
23  OAK        95    0.659
24  DET        92    0.589
25  MIA        91    0.689
26  PIT        89    0.609
27  WSN        88    0.678
28  KCR        85    0.584
29  CLE        71    0.623

### Findings

ATL, LAD, and LAA recorded the highest team home run totals in the dataset. However, teams with the most home runs did not always have the highest average OPS. For example, MIL and PHI ranked among the league leaders in average OPS despite recording fewer total home runs than several other teams. This suggests that offensive production is influenced by factors beyond home run hitting alone.

## Research Question 3

Which teams demonstrated the strongest plate discipline based on walk-to-strikeout ratio?

In [19]:
query = """
SELECT Tm,
       ROUND(
           SUM(BB) * 1.0 / SUM(SO),
           3
       ) AS BB_SO_Ratio
FROM batting
WHERE Tm != 'TOT'
GROUP BY Tm
ORDER BY BB_SO_Ratio DESC;
"""

pd.read_sql_query(query, conn)

     Tm  BB_SO_Ratio
0   SDP        0.493
1   LAD        0.484
2   ARI        0.423
3   NYM        0.420
4   CLE        0.419
5   STL        0.412
6   ATL        0.409
7   TOR        0.405
8   TEX        0.403
9   CIN        0.403
10  HOU        0.402
11  BAL        0.398
12  CHC        0.396
13  PIT        0.394
14  LAA        0.391
15  BOS        0.385
16  MIL        0.382
17  NYY        0.379
18  TBR        0.370
19  SFG        0.360
20  DET        0.360
21  OAK        0.358
22  WSN        0.346
23  SEA        0.340
24  MIA        0.336
25  MIN        0.328
26  PHI        0.326
27  COL        0.298
28  KCR        0.281
29  CHW        0.279

### Findings

SDP and LAD recorded the highest walk-to-strikeout ratios in the dataset, followed by ARI, NYM, and CLE. These teams generated walks at a higher rate relative to strikeouts, suggesting stronger plate discipline and a greater ability to avoid unproductive plate appearances.

## Research Question 4

Which players generated strong offensive production despite relatively low home run totals?

In [22]:
query = """
SELECT Name,
       Tm,
       PA,
       HR,
       ROUND(OPS,3) AS OPS
FROM batting
WHERE OPS >= 0.850
  AND HR < 20
  AND PA >= 100
ORDER BY OPS DESC;
"""

pd.read_sql_query(query, conn)

                  Name   Tm   PA  HR    OPS
0          Aaron Judge  NYY  213  19  1.078
1        Corey Seager*  TEX  298  15  1.044
2       Mickey Moniak*  LAA  173  11  0.988
3      Yordan Alvarez*  HOU  242  17  0.978
4      Edouard Julien*  MIN  183   9  0.941
5          Sean Murphy  ATL  297  17  0.935
6           Juan Soto*  SDP  438  19  0.928
7         Will Benson*  CIN  164   6  0.912
8      Cody Bellinger*  CHC  283  13  0.910
9          Matt McLain  CIN  268  10  0.898
10          Yandy Díaz  TBR  367  13  0.897
11         Luke Raley*  TBR  272  15  0.896
12        Kyle Tucker*  HOU  411  17  0.895
13        Luis Arraez*  MIA  399   3  0.892
14      Chas McCormick  HOU  232  12  0.892
15          Will Smith  LAD  325  13  0.892
16          Mike Ford*  SEA  119  10  0.889
17       Jarren Duran*  BOS  278   6  0.883
18   Masataka Yoshida*  BOS  370  11  0.883
19       Wilmer Flores  SFG  233  12  0.878
20        Ketel Marte#  ARI  403  17  0.876
21        Josh Naylor*  CLE  351  15  0.869
22       Austin Slater  SFG  103   4  0.867
23       Isaac Paredes  TBR  330  18  0.864
24       José Ramírez#  CLE  421  14  0.863
25  Fernando Tatis Jr.  SDP  365  17  0.863
26          Mike Trout  LAA  358  18  0.862
27   Christopher Morel  CHC  232  15  0.860
28        Nolan Jones*  COL  158   8  0.858
29       Ryan O'Hearn*  BAL  175   7  0.857
30          Tom Murphy  SEA  117   6  0.856
31   Christian Yelich*  MIL  410  14  0.851
32         Jose Altuve  HOU  143   6  0.850

### Findings

Several players maintained strong offensive performance despite recording fewer than 20 home runs. Notably, Luis Arraez posted an OPS of .892 with only three home runs, while Juan Soto and Yandy Díaz recorded OPS values above .890 without relying heavily on home run production. These results suggest that offensive value can be generated through on-base ability, contact hitting, and overall offensive consistency rather than home run power alone.

## Conclusion

This project explored offensive performance trends across MLB teams and players using SQL. While teams such as ATL led the league in home run production, teams including MIL and PHI ranked highest in average OPS. In addition, players such as Luis Arraez and Juan Soto maintained strong offensive performance despite relatively low home run totals. These findings suggest that offensive success cannot be explained by home run production alone and is influenced by multiple factors, including plate discipline, on-base ability, and overall offensive consistency. This analysis demonstrates how SQL can be used to explore sports data, identify trends, and generate insights from large datasets.